// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHkFRgsKzEqpB9f-QmU9laZ2NxBDebxBQ',
    appId: '1:715021431084:web:dac7d40cfe03ac262f3c89',
    messagingSenderId: '715021431084',
    projectId: 'tictac-ea485',
    authDomain: 'tictac-ea485.firebaseapp.com',
    storageBucket: 'tictac-ea485.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1UeJAP7vZnB72k04pDC7nxjzU_5Kt3go',
    appId: '1:715021431084:android:1555037678e93cb42f3c89',
    messagingSenderId: '715021431084',
    projectId: 'tictac-ea485',
    storageBucket: 'tictac-ea485.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGXsLrgcHssQOP2b599AgIMvqEOCMjZdw',
    appId: '1:715021431084:ios:7d966a53b6b12ff42f3c89',
    messagingSenderId: '715021431084',
    projectId: 'tictac-ea485',
    storageBucket: 'tictac-ea485.appspot.com',
    iosBundleId: 'com.example.flutterEh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGXsLrgcHssQOP2b599AgIMvqEOCMjZdw',
    appId: '1:715021431084:ios:7d966a53b6b12ff42f3c89',
    messagingSenderId: '715021431084',
    projectId: 'tictac-ea485',
    storageBucket: 'tictac-ea485.appspot.com',
    iosBundleId: 'com.example.flutterEh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHkFRgsKzEqpB9f-QmU9laZ2NxBDebxBQ',
    appId: '1:715021431084:web:6a92c9bb9383582a2f3c89',
    messagingSenderId: '715021431084',
    projectId: 'tictac-ea485',
    authDomain: 'tictac-ea485.firebaseapp.com',
    storageBucket: 'tictac-ea485.appspot.com',
  );
}
